### ISSUE TITLE
手机浏览器播放没有声音是怎么回事？

### ISSUE THREAD

**Issue by jason469618528** [jsososo/MixMusicApi#1]

**Comment by jsososo** [comment]
目前默认是使用 AudioContext，如果不是音乐加载问题，那就可能是这方面的支持问题

2020年9月26日 上午8:21，jason469618528 <notifications@github.com<mailto:notifications@github.com>> 写道：

**Comment by jason469618528** [comment]
就是支持方面的问题。。。作者可以试试

**Comment by jason469618528** [comment]
> 目前默认是使用 AudioContext，如果不是音乐加载问题，那就可能是这方面的支持问题

 @jsososo  作者看下这个有没有效果 https://blog.csdn.net/CCUKER/article/details/79819538
