### ISSUE TITLE
运行故障

### ISSUE THREAD

**Issue by avataratom** [jsososo/MixMusicApi#4]
搭建服务时，Request类的第17行  request = async (obj) => {报错

**Comment by jsososo** [comment]
检查下node版本，建议12+

2021年5月25日 下午3:49，avataratom ***@***.******@***.***>> 写道：



搭建服务时，Request类的第17行 request = async (obj) => {报错

**Comment by avataratom** [comment]
谢谢大佬啊，就是这个问题
